name: synchronize-with-repo2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GRAMMAR_REPOSITORY_TOKEN: $GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn grammar:download
    - run: yarn grammar:build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: "Grammar releas synchronization"
