name: synchronize-with-repo2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - name: Use Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install -g yarn
      - run: yarn
      - run: yarn grammar:download
      - run: yarn grammar:build
      - name: Create New Branch
        run: |
          git switch -c update_grammar-$(cat ./public/tag.txt)
          git add .
          git commit -m "updated grammar source code;"
          git push -u origin update_grammar-$(cat ./public/tag.txt)
          gh pr create -B main -H update_grammar-$(cat ./public/tag.txt) --title 'Grammar Update' --body 'Updated grammar sources from grammar repository changes.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
