name: synchronize-with-repo2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: 1arp/create-a-file-action@0.4.5
      with:
        path: '.'
        isAbsolutePath: false
        file: '.env'
        content: |
          GITHUB_TOKEN=${{ secrets.BUILD_TOKEN }}
    - name: Use Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn grammar:download
    - run: yarn grammar:build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: "Grammar releas synchronization"
