name: synchronize-with-repo2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - name: Use Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install -g yarn
      - name: Create Update Grammar Branch
        run: |
          git switch -c update_grammar
      - name: Build Grammar Sources
        run: |
          yarn
          yarn grammar:download
          yarn grammar:build
      - name: Check For Any Changes
        id: check
        run: |
          CHANGED_FILES=$(git diff --name-only $(git merge-base --fork-point remotes/origin/main || git merge-base remotes/origin/main HEAD))
          if [ -n "$CHANGED_FILES" ]; then
            echo "skip_steps=false" >> $GITHUB_OUTPUT
          else
            echo "skip_steps=true" >> $GITHUB_OUTPUT
          fi
      - name: Create Update Grammar Pull Request
        if: steps.check.outputs.skip_steps != 'true'
        run: |
          git add .
          git commit -m "updated grammar source code;"
          git push -u origin update_grammar --force
          gh pr create -B main -H update_grammar --title 'Grammar Update' --body 'Updated grammar sources from grammar repository changes.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
